//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APICliente.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendasCliente
    {
        public int Codigo { get; set; }
        public System.DateTime Data_Venda { get; set; }
        public double Valor_Venda { get; set; }
    }
}
